eyewitness-web/src/main/java/tn/esprit/alphateam/mBeans/UserServicesBean.java
package tn.esprit.alphateam.mBeans;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.Part;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.Response;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.SignatureException;
import tn.esprit.alphateam.eyewitness.persistence.AgentRequest;
import tn.esprit.alphateam.eyewitness.persistence.Notification;
import tn.esprit.alphateam.eyewitness.persistence.User;
import tn.esprit.alphateam.eyewitness.services.interfaces.NotificationServicesLocal;
import tn.esprit.alphateam.eyewitness.services.interfaces.UserServicesLocal;
import tn.esprit.alphateam.util.JwtServices;

@ManagedBean
@ViewScoped
public class UserServicesBean implements Serializable{

	private User user = new User();
	private Part userAvatar;
	private List<Notification> currentUserNotifications;

	private List<User> bannableUsers = new ArrayList<>();
	private List<User> bannedUsers = new ArrayList<>();
	private List<User> agents = new ArrayList<>();
	private int durationDays;
	private AgentRequest agentRequest = new AgentRequest();
	private List<AgentRequest> agentRequests = new ArrayList<>();
	private List<AgentRequest> agentRequestValid= new ArrayList<>();
	
	@EJB
	private UserServicesLocal userServicesLocal;

	@EJB
	private JwtServices jwtServices;
	
	@EJB
	private NotificationServicesLocal notificationServicesLocal;
	
	@PostConstruct
	public void init() {
		User user = getCurrentUser();
		
		if (user != null) {
			currentUserNotifications = notificationServicesLocal.findFiveLastNotificationsByUserId(user.getId());
			doFindBannableUser();
			doFindBannedUser();
			doFindAgentRequest();
			doFindAgentRequestValid();
		}
		
	}
	
	public String doRemoteLogin() {
		String returnUrl = "";
		Client client = ClientBuilder.newClient();

		WebTarget target = client.target("http://localhost:50279/api/UserApi")
				.path("Login")
				.queryParam("email", user.getEmail())
				.queryParam("password", user.getPassword());
		
		Response response = target.request().get();

		User loggedInUser = response.readEntity(User.class);

		if (loggedInUser != null) {

			// Generate JWT
			String jwt = null;
			jwt = jwtServices.generateToken(loggedInUser);

			jwtServices.setTokenForCurrentUser(jwt);

			if (loggedInUser.getRole().equals("ADMIN"))
				returnUrl = "/pages/secure/admin/tab?faces-redirect=true";
			else
				returnUrl = "/pages/public/home?faces-redirect=true";
			
		} else {
			System.out.println("LOGIN ERROR");
		}

		response.close();
		client.close();
		
		return returnUrl;
	}

	public String doLogin() {
		System.out.println("Doing login !");
		String returnUrl = "";

		User loggedInUser = userServicesLocal.login(user.getEmail(), user.getPassword());

		if (loggedInUser != null) {

			// Generate JWT
			String jwt = null;
			jwt = jwtServices.generateToken(loggedInUser);

			jwtServices.setTokenForCurrentUser(jwt);

			if (loggedInUser.getRole().equals("ADMIN"))
				returnUrl = "/pages/secure/admin/admin?faces-redirect=true";
			else
				returnUrl = "/pages/public/home?faces-redirect=true";
			
		} else {
			System.out.println("LOGIN ERROR");
		}

		return returnUrl;
	}

	public String doRegister() {
		
		// Upload images to Content folder configured on wildfly undertow subsystem
		String avatarsPath = System.getProperty("jboss.home.dir") + "\\eyewitness-content\\avatars";
		String fileName = userAvatar.getSubmittedFileName();
		String fileExtension = fileName.substring(fileName.lastIndexOf("."), fileName.length());
		String filePath = user.getEmail() + "_" + user.getId() + fileExtension;
		
		try (InputStream input = userAvatar.getInputStream()) {
	        Files.copy(input, new File(avatarsPath, filePath).toPath());
	    }
	    catch (IOException e) {
	    	e.printStackTrace();
	    }

		user.setAvatar(filePath);
		userServicesLocal.register(user);

		return "/pages/public/login?faces-redirect=true";
	}

	public String logout() {
		String returnUrl = "/pages/public/home?faces-redirect=true";

		// Remove JWT
		jwtServices.invalidateToken();

		return returnUrl;
	}
	
	public void doSendEmailToUser(String message, String subject, String userEmail) {
		userServicesLocal.sendEmailToUser(message, subject, userEmail);
	}
	
	public void doFindBannableUser() {

		bannableUsers = userServicesLocal.findBannableUsers();

	}

	public String doAssignAgent() {

		userServicesLocal.assignAgent(agentRequest);
		return "/pages/secure/admin/tab?faces-redirect=true";

	}

	public String doBanUser() {
       System.out.println(durationDays);
		userServicesLocal.banUser(user.getId(), durationDays);
		userServicesLocal.sendEmailToUser("You have been banned for "+ durationDays + " days", "BAN FROM EYEWITNESS",
				user.getEmail());
		return "/pages/secure/admin/tab?faces-redirect=true";
	}

	public void doFindBannedUser() {

		bannedUsers = userServicesLocal.findBannedUsers();
	}

	public String doUnbanUser() {
		userServicesLocal.unbanUser(user.getId());
		return "/pages/secure/admin/tab?faces-redirect=true";

	}
	

	public void doFindAgents() {

		agents = userServicesLocal.findAgents();

	}

	public String doDemoteAgent() {

		userServicesLocal.demoteAgent(agentRequest);
		return "/pages/secure/admin/tab?faces-redirect=true";

	}

	public void doFindAgentRequestValid() {

		agentRequestValid = userServicesLocal.findAgentRequestActive();

	}

	public void doFindAgentRequest() {

		agentRequests = userServicesLocal.findAgentRequest();

	}

	public User getCurrentUser() {
		User user = null;
		try {
			HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext()
					.getRequest();

			String jwt = jwtServices.getTokenFromRequest(request);

			String id = null;
			if (jwt != null) {
				try {

					Claims claims = jwtServices.validateToken(jwt);

					id = claims.getId();
				} catch (SignatureException e) {

					System.err.println("Can't trust token !");
					e.printStackTrace();
				} catch (Exception e) {
					System.err.println("Token is null => no current User");
					return user;
				}

				user = userServicesLocal.findUserById(Integer.parseInt(id));
			}

		} catch (Exception e) {
			System.err.println("Error while getting user !");
			e.printStackTrace();
		}

		return user;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Part getUserAvatar() {
		return userAvatar;
	}

	public void setUserAvatar(Part userAvatar) {
		this.userAvatar = userAvatar;
	}

	public List<Notification> getCurrentUserNotifications() {
		return currentUserNotifications;
	}

	public void setCurrentUserNotifications(List<Notification> currentUserNotifications) {
		this.currentUserNotifications = currentUserNotifications;
	}

	public List<User> getBannableUsers() {
		return bannableUsers;
	}

	public void setBannableUsers(List<User> bannableUsers) {
		this.bannableUsers = bannableUsers;
	}

	public List<User> getBannedUsers() {
		return bannedUsers;
	}

	public void setBannedUsers(List<User> bannedUsers) {
		this.bannedUsers = bannedUsers;
	}

	public List<User> getAgents() {
		return agents;
	}

	public void setAgents(List<User> agents) {
		this.agents = agents;
	}

	public int getDurationDays() {
		return durationDays;
	}

	public void setDurationDays(int durationDays) {
		this.durationDays = durationDays;
	}

	public AgentRequest getAgentRequest() {
		return agentRequest;
	}

	public void setAgentRequest(AgentRequest agentRequest) {
		this.agentRequest = agentRequest;
	}

	public List<AgentRequest> getAgentRequests() {
		return agentRequests;
	}

	public void setAgentRequests(List<AgentRequest> agentRequests) {
		this.agentRequests = agentRequests;
	}

	public List<AgentRequest> getAgentRequestValid() {
		return agentRequestValid;
	}

	public void setAgentRequestValid(List<AgentRequest> agentRequestValid) {
		this.agentRequestValid = agentRequestValid;
	}
	
}

eyewitness-web/src/main/webapp/pages/secure/user/chartView.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	template="/WEB-INF/template/template.xhtml"
	xmlns:p="http://primefaces.org/ui">
	<ui:define name="content">

		<p:chart type="bar" model="#{participationChartView.barModel}" style="height:300px" />

	</ui:define>
</ui:composition>

eyewitness-web/src/main/webapp/pages/secure/user/eventSchedule.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/template/template.xhtml">
	<ui:define name="title">Schedule page</ui:define>
	<ui:define name="content">
		<h:form>
			<p:growl id="messages" showDetail="true" />

			<h:panelGrid columnClasses="value">
				<h3 style="margin-top: 0">Editable Schedule</h3>
				<p:schedule id="schedule" value="#{scheduleView.eventModel}"
					widgetVar="myschedule" timeZone="GMT+1">

					<p:ajax event="dateSelect" listener="#{scheduleView.onDateSelect}"
						update="eventDetails" oncomplete="PF('eventDialog').show();" />
					<p:ajax event="eventSelect"
						listener="#{scheduleView.onEventSelect}" update="eventDetails"
						oncomplete="PF('eventDialog').show();" />
					<p:ajax event="eventMove" listener="#{scheduleView.onEventMove}"
						update="messages" />
					<p:ajax event="eventResize"
						listener="#{scheduleView.onEventResize}" update="messages" />

				</p:schedule>

			</h:panelGrid>

			<p:dialog widgetVar="eventDialog" header="Event Details"
				showEffect="clip" hideEffect="clip">
				<h:panelGrid id="eventDetails" columns="2">
					<p:outputLabel for="title" value="Titles:" />
					<p:inputText id="title" value="#{scheduleView.event.title}"
						required="true" />

					<p:outputLabel for="from" value="From:" />
					<p:calendar id="from" value="#{scheduleView.event.startDate}"
						timeZone="GMT+2" pattern="dd/MM/yyyy HH:mm" />

					<p:outputLabel for="to" value="To:" />
					<p:calendar id="to" value="#{scheduleView.event.endDate}"
						timeZone="GMT+2" pattern="dd/MM/yyyy HH:mm" />

					<p:outputLabel for="allDay" value="All Day:" />
					<h:selectBooleanCheckbox id="allDay"
						value="#{scheduleView.event.allDay}" />

					<p:commandButton type="reset" value="Reset" />
					<p:commandButton id="addButton" value="Save"
						actionListener="#{scheduleView.addEvent}"
						oncomplete="PF('myschedule').update();PF('eventDialog').hide();" />
				</h:panelGrid>
			</p:dialog>
		</h:form>

		<style type="text/css">
.value {
	width: 1000px;
}
</style>


	</ui:define>


</ui:composition>

eyewitness-web/src/main/webapp/pages/secure/user/participate.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	template="/WEB-INF/template/template.xhtml">
	<ui:define name="title">Home page</ui:define>
	<ui:define name="content">
		<h:form>
			<h:dataTable value="#{competitionsServicesBean.competitionList}"
				var="p" border="5">
				<h:column id="c12">
					<f:facet name="header">
						<h:outputText value="Theme" />
					</f:facet>
					<h:outputText value="#{p.theme}" />
					<f:facet name="header">
						<h:outputText value="Description" />
					</f:facet>
					<h:outputText value="#{p.descripiton}" />
					<f:facet name="header">
						<h:outputText value="DateFrom" />
					</f:facet>
					<h:outputText value="#{p.dateFrom}" />
					<f:facet name="header">
						<h:outputText value="DateTo" />
					</f:facet>
					<h:outputText value="#{p.dateTo}" />
					<f:facet name="header">
						<f:facet name="header">
							<h:outputText value="witnesscard" />
						</f:facet>
						<h:outputText value="#{p.witnesscard.name}" />
						<f:facet name="header">
							<h:outputText value="Actions" />
						</f:facet>
						<h:commandLink
							action="#{witnessCardsServicesBean.doparticipateCompetition(p)}"
							value="participate">
						</h:commandLink>
					</f:facet>
				</h:column>
			</h:dataTable>

		</h:form>
	</ui:define>
</ui:composition>

eyewitness-web/src/main/webapp/pages/secure/user/participateEvent.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	template="/WEB-INF/template/template.xhtml">
	<ui:define name="title">List Events</ui:define>
	<ui:define name="content">

		<h:body>
			<ui:repeat var="e"
				value="#{ eventManagementBean.eventsunparticipated}">
				<div class="row">
					<div class="col s12 m7">
						<div class="card">
							<div class="card-image">
								<h:graphicImage value="/content/#{e.picture}" />
								<span style="background-color: red" class="card-title">#{e.name}</span>
							</div>
							<div class="card-content">
								<p>#{e.description}</p>
								<p style="color: red">Date From : #{e.dateFrom}</p>
								<p style="color: red">Date To: #{e.dateTo}</p>
							</div>

							<div class="card-action">
								<h:form>
									<h:commandLink class="waves-effect waves-green btn-flat"
										rendered="#{eventManagementBean.doVerifyDateParticipation(e,eventManagementBean.currentUser.id)}"
										action="#{eventManagementBean.doParticipate(eventManagementBean.currentUser.id, e)}"
										value="Participate" />
									<h:commandLink
										onclick="Materialize.toast('You can not participate in this event because you have already an event in the same date', 130000)"
										class="waves-effect waves-green btn-flat "
										rendered="#{!eventManagementBean.doVerifyDateParticipation(e,eventManagementBean.currentUser.id)}"
										value="Participate" />

								</h:form>

							</div>


							<ui:repeat var="u"
								value="#{eventManagementBean.dolistFollowedUsersByEvent(e.id,eventManagementBean.currentUser.id)}">

								<div class="chip">
									<h:graphicImage value="/content/#{u.avatar}"
										alt="Contact Person" />
									#{u.firstName} #{u.lastName}
								</div>

							</ui:repeat>

						</div>
					</div>
				</div>

			</ui:repeat>



		</h:body>
	</ui:define>
</ui:composition>

eyewitness-web/src/main/webapp/pages/secure/user/userHome.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	template="/WEB-INF/template/template.xhtml">
	<ui:define name="title"> User space</ui:define>
	<ui:define name="content">

		<h1>
			Welcome User :
			<h:outputText
				value="#{userServicesBean.currentUser ne null ? userServicesBean.currentUser.firstName : ''} #{userServicesBean.currentUser ne null ? userServicesBean.currentUser.lastName : ''}" />
		</h1>

		<h:form id="chercherWC" rendered="#{witnessCardsServicesBean.displaysearch}">
			<h:inputText value="#{witnessCardsServicesBean.searchWCString}" />
			<h:commandButton  action="#{witnessCardsServicesBean.doSearchWCbyName()}" value="search" />
		</h:form>


		<h:form id="WClist" rendered="#{witnessCardsServicesBean.displayFormWc}">
			<h:dataTable value="#{witnessCardsServicesBean.witnessCards}" var="p"
				border="2">
				<h:column id="c1">
					<f:facet name="header">
						<h:outputText value=" Witness Card" />
					</f:facet>
					<h:outputText value="#{p.name}" />
				</h:column>

				<h:column id="c3">
					<f:facet name="header">
						<h:outputText value=" Description" />
					</f:facet>
					<h:outputText value="#{p.description}" />
				</h:column>

				<h:column id="c2">
					<f:facet name="header">
                      <h:outputText value="" /> 
					</f:facet>

					<h:commandButton  action="#{witnessCardsServicesBean.doCheckWitnessCard(p)}" value="Check it !" />

				</h:column>
			</h:dataTable>
		</h:form>
		
		<h:form id="ckdelaul" rendered="#{witnessCardsServicesBean.displayWCDetails}">
			<h:dataTable value="#{witnessCardsServicesBean.witnessCards}" var="k" border="2">
				<h:column id="c4">
					<f:facet name="header">
						<h:outputText value="" />
					</f:facet>
					<h:graphicImage value="#{k.picture}" width="200"  height="200"/> <br/>
					<h:outputText value="#{k.description}" />
				</h:column>
				
			</h:dataTable>

		</h:form>


		<h:form id="listofcomment" rendered="#{witnessCardsServicesBean.displayComment}">
			<h:dataTable value="#{witnessCardsServicesBean.commentsOfWitnessCard}" var="k" border="2">
				<h:column id="c4">
					<f:facet name="header">
						<h:outputText value="" />
					</f:facet>
					<h:outputText value="#{k.userName}" />
				</h:column>
				<h:column id="c5">
					<f:facet name="header">
						<h:outputText value="" />
					</f:facet>
					<h:outputText value="#{k.comment}" />
				</h:column>
			</h:dataTable>

				<h:inputText value="#{witnessCardsServicesBean.commentText}" />
			<h:commandButton  action="#{witnessCardsServicesBean.doCommenterwintnesscard()}" value="comment" />
		</h:form>






	</ui:define>
</ui:composition>